# Generated by Django 5.2 on 2025-10-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='news/header/')),
                ('description', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='news/images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='news/images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='news/images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='news/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
    ]
